//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GEOSERVER;Initial Catalog=Trenes;Persist Security Info=True;User ID=s" +
            "a;Password=gps38012")]
        public string TrenesConnectionString1 {
            get {
                return ((string)(this["TrenesConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GEOSERVER;Initial Catalog=Trenes;Persist Security Info=True;User ID=s" +
            "a;Password=gps38012")]
        public string TrenesConnectionString {
            get {
                return ((string)(this["TrenesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GEOSERVER;Initial Catalog=Trenes;Persist Security Info=True;User ID=s" +
            "a")]
        public string TrenesConnectionString2 {
            get {
                return ((string)(this["TrenesConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=URIELGOLAB;Initial Catalog=TrenesDes;Persist Security Info=True;User " +
            "ID=sa")]
        public string TrenesDesConnectionString {
            get {
                return ((string)(this["TrenesDesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=146.26.1.7;Initial Catalog=TrenesProd;User ID=sa")]
        public string TrenesProdConnectionString {
            get {
                return ((string)(this["TrenesProdConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=146.26.1.7;Initial Catalog=TrenesProd;Persist Security Info=True;User" +
            " ID=sa")]
        public string TrenesProdConnectionString1 {
            get {
                return ((string)(this["TrenesProdConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JUAN\\SOFLEXSERVER;Persist Security Info=True;User ID=sa")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JUAN\\SOFLEXSERVER;Initial Catalog=TrenesDes;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string TrenesDesConnectionString1 {
            get {
                return ((string)(this["TrenesDesConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=juan\\soflexserver;Initial Catalog=TrenesDes;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string TrenesDesConnectionString2 {
            get {
                return ((string)(this["TrenesDesConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FER\\SQLEXPRESSR2;Initial Catalog=TrenesDes;Persist Security Info=True" +
            ";User ID=sa")]
        public string TrenesDesConnectionString3 {
            get {
                return ((string)(this["TrenesDesConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SOFLEXSERVER\\SOFLEXSERVER;Initial Catalog=TrenesDes;Persist Security " +
            "Info=True;User ID=sa")]
        public string TrenesDesConnectionString4 {
            get {
                return ((string)(this["TrenesDesConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SOFLEXSERVER\\SOFLEXSERVER;Initial Catalog=TrenesDes;User ID=sa")]
        public string TrenesDesConnectionString5 {
            get {
                return ((string)(this["TrenesDesConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STELLA-NB\\SQLEXPRESS;Initial Catalog=TrenesMimico;Persist Security In" +
            "fo=True;User ID=sa")]
        public string TrenesMimicoConnectionString {
            get {
                return ((string)(this["TrenesMimicoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=STELLA-NB\\SQLEXPRESS;Initial Catalog=TrenesMimico;Persist Security In" +
            "fo=True;User ID=sa;Password=Sat322401")]
        public string TrenesMimicoConnectionString1 {
            get {
                return ((string)(this["TrenesMimicoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=server04.soflex.com.ar;Initial Catalog=Uriel;User ID=Uriel")]
        public string UrielConnectionString {
            get {
                return ((string)(this["UrielConnectionString"]));
            }
        }
    }
}
