'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CenturServiceSOAP
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CenturServiceSOAP.ICenturServiceSOAP")>  _
    Public Interface ICenturServiceSOAP
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICenturServiceSOAP/BuscarServicio", ReplyAction:="http://tempuri.org/ICenturServiceSOAP/BuscarServicioResponse")>  _
        Function BuscarServicio(ByVal zona As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICenturServiceSOAP/BuscarServicio2", ReplyAction:="http://tempuri.org/ICenturServiceSOAP/BuscarServicio2Response")>  _
        Function BuscarServicio2(ByVal zona As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICenturServiceSOAPChannel
        Inherits CenturServiceSOAP.ICenturServiceSOAP, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CenturServiceSOAPClient
        Inherits System.ServiceModel.ClientBase(Of CenturServiceSOAP.ICenturServiceSOAP)
        Implements CenturServiceSOAP.ICenturServiceSOAP
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function BuscarServicio(ByVal zona As String) As String Implements CenturServiceSOAP.ICenturServiceSOAP.BuscarServicio
            Return MyBase.Channel.BuscarServicio(zona)
        End Function
        
        Public Function BuscarServicio2(ByVal zona As String) As String Implements CenturServiceSOAP.ICenturServiceSOAP.BuscarServicio2
            Return MyBase.Channel.BuscarServicio2(zona)
        End Function
    End Class
End Namespace
