'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CrearServicioP4

    '''<summary>
    '''txtDiasAntes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiasAntes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiasDespues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiasDespues As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkPrivado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPrivado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''grdPrivacidadGrupos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPrivacidadGrupos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tbServicioGrupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbServicioGrupo As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''dpServicioGrupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpServicioGrupo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btAgregarGrupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAgregarGrupo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkAgregarOtroGrupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAgregarOtroGrupo As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkConfirmarTurno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConfirmarTurno As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnviarRecordatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnviarRecordatorio As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSobreturno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSobreturno As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMercadoPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMercadoPago As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnFinalizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinalizar As Global.System.Web.UI.WebControls.Button
End Class
