#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Uriel")]
	public partial class DC : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertServicio(Servicio instance);
    partial void UpdateServicio(Servicio instance);
    partial void DeleteServicio(Servicio instance);
    #endregion
		
		public DC(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DC(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DC(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DC(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Perfil> Perfils
		{
			get
			{
				return this.GetTable<Perfil>();
			}
		}
		
		public System.Data.Linq.Table<Zona> Zonas
		{
			get
			{
				return this.GetTable<Zona>();
			}
		}
		
		public System.Data.Linq.Table<Servicio> Servicios
		{
			get
			{
				return this.GetTable<Servicio>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Perfil")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Perfil
	{
		
		private string _idPerfil;
		
		private string _descrPerfil;
		
		public Perfil()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPerfil", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string idPerfil
		{
			get
			{
				return this._idPerfil;
			}
			set
			{
				if ((this._idPerfil != value))
				{
					this._idPerfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrPerfil", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string descrPerfil
		{
			get
			{
				return this._descrPerfil;
			}
			set
			{
				if ((this._descrPerfil != value))
				{
					this._descrPerfil = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zona")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Zona
	{
		
		private System.Nullable<int> _idZona;
		
		private string _descrZona;
		
		public Zona()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idZona", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public System.Nullable<int> idZona
		{
			get
			{
				return this._idZona;
			}
			set
			{
				if ((this._idZona != value))
				{
					this._idZona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrZona", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string descrZona
		{
			get
			{
				return this._descrZona;
			}
			set
			{
				if ((this._descrZona != value))
				{
					this._descrZona = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicio")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idServicio;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _idCategoria;
		
		private string _idZona;
		
		private System.Data.Linq.Binary _Imagen;
		
		private string _idProveedor;
		
		private string _Observaciones;
		
		private string _Grillas;
		
		private string _Reglas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidServicioChanging(int value);
    partial void OnidServicioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnidCategoriaChanging(string value);
    partial void OnidCategoriaChanged();
    partial void OnidZonaChanging(string value);
    partial void OnidZonaChanged();
    partial void OnImagenChanging(System.Data.Linq.Binary value);
    partial void OnImagenChanged();
    partial void OnidProveedorChanging(string value);
    partial void OnidProveedorChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnGrillasChanging(string value);
    partial void OnGrillasChanged();
    partial void OnReglasChanging(string value);
    partial void OnReglasChanged();
    #endregion
		
		public Servicio()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idServicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int idServicio
		{
			get
			{
				return this._idServicio;
			}
			set
			{
				if ((this._idServicio != value))
				{
					this.OnidServicioChanging(value);
					this.SendPropertyChanging();
					this._idServicio = value;
					this.SendPropertyChanged("idServicio");
					this.OnidServicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(255)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idZona", DbType="VarChar(50)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string idZona
		{
			get
			{
				return this._idZona;
			}
			set
			{
				if ((this._idZona != value))
				{
					this.OnidZonaChanging(value);
					this.SendPropertyChanging();
					this._idZona = value;
					this.SendPropertyChanged("idZona");
					this.OnidZonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProveedor", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string idProveedor
		{
			get
			{
				return this._idProveedor;
			}
			set
			{
				if ((this._idProveedor != value))
				{
					this.OnidProveedorChanging(value);
					this.SendPropertyChanging();
					this._idProveedor = value;
					this.SendPropertyChanged("idProveedor");
					this.OnidProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grillas", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string Grillas
		{
			get
			{
				return this._Grillas;
			}
			set
			{
				if ((this._Grillas != value))
				{
					this.OnGrillasChanging(value);
					this.SendPropertyChanging();
					this._Grillas = value;
					this.SendPropertyChanged("Grillas");
					this.OnGrillasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reglas", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string Reglas
		{
			get
			{
				return this._Reglas;
			}
			set
			{
				if ((this._Reglas != value))
				{
					this.OnReglasChanging(value);
					this.SendPropertyChanging();
					this._Reglas = value;
					this.SendPropertyChanged("Reglas");
					this.OnReglasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Usuario
	{
		
		private string _idUsuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Password;
		
		private string _Email;
		
		private string _Telefono;
		
		private string _idPerfil;
		
		public Usuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this._idUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPerfil", DbType="NChar(10)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string idPerfil
		{
			get
			{
				return this._idPerfil;
			}
			set
			{
				if ((this._idPerfil != value))
				{
					this._idPerfil = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
