'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VerEstadisticas

    '''<summary>
    '''Estadistica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Estadistica As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''DDLServicios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLServicios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FechaDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaDesde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FechaHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaHasta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HoraDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoraDesde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HoraHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoraHasta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalcularEstadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalcularEstadisticas As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BorrarEstadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BorrarEstadisticas As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultado As Global.System.Web.UI.WebControls.Label
End Class
